### PR TITLE
Disable decompression of body for Cronet usecases

### PR DESCRIPTION
**Pull request by ssavant-pfpt**
Here in this case FilterSourceStream  is decompressing the body as we get it back from Cronet. 
That mismatches with headers information received via destination. 
HTTP responses should stay unaltered for our use cases, so disable stream(body) decompression here.
(And clients can perform that if needed on client side?)

### CODE REVIEW

**Comment by wwwsevolod** [comment]
@ssavant-pfpt I was thinking about this lately — this change makes us having two forks of chromium. But maybe we should introduce a compilation time flag that would make this optional — it would make a change cleaner (no unnecessary commenting of the code that we don't really touch) and also would allow us to maintain only one fork of chrome

**Comment by asmirnou** [comment]
If we gonna compile not only Cronet, but Chromium out of this branch, this change will break it. It needs to be behind some flag set up at either build or runtime.

**Comment by ssavant-pfpt** [comment]
That's a valid point. @wwwsevolod  and @asmirnou 
Let me find other option for this.
May be use some flag to provide different implementation of this method or something. Let me get back here after little exploration.

**Comment by asmirnou** [comment]
We can let it decompress the body, but then remove / change `Content-Encoding` header in the response and pass the latter down the road, can't we?

**Comment by wwwsevolod** [comment]
@asmirnou in this case we would also have to remove content length and handle connection closures differently, and also it means changing traffic and the goal is to try to avoid it

**Comment by ssavant-pfpt** [comment]
> We can let it decompress the body, but then remove / change `Content-Encoding` header in the response and pass the latter down the road, can't we?

@asmirnou and @wwwsevolod 
I have tried this option already where we remove this Content Encoding as well as Content Length headers on golang side via a flag on golang HTTP side, and what @wwwsevolod said is true. 
Then browser doesn't behave well and doesn't load the page with agent's proxy. 
CURL as client works fine with it but Chromium somehow expects things differently and shuts the connection with it.

**Comment by asmirnou** [comment]
Encoding of content is optional and can be turned off by the website itself. Chromium/Cronet handle that perfectly. From chromium perspective which hop has disabled/decoded the content doesn't matter and is transparent.

**Comment by ssavant-pfpt** [comment]
> Encoding of content is optional and can be turned off by the website itself. Chromium/Cronet handle that perfectly. From chromium perspective which hop has disabled/decoded the content doesn't matter and is transparent.

Yes that's correct and I can see technically each involved party should be able to handle it well. And I also found out on golang on http package, there is a flag which can help us do that. [Uncompressed bool flag on Response in http package](https://pkg.go.dev/net/http#Response)
Just this means changing traffic (HTTP headers) as @wwwsevolod  mentioned above, which we didn't want to do in the first place and was one of the goal of this whole network fingerprinting exercise. :) 


That being said @asmirnou and @wwwsevolod  I was able to achieve this via build feature flag as we were discussing above. And that seems much clearer. Here is the [PR](https://github.com/weblifeio/chromium/pull/6). So closing this and we can continue the discussion on other PR mentioned above. Thanks

**Comment by ssavant-pfpt** [comment]
Closing this and continuing further on https://github.com/weblifeio/chromium/pull/6

**Pull request closed without merging**
